[package]
name = "seer"
version = "0.1.0"
edition = "2021"

[lib]
name = "seer"
crate-type = ["cdylib", "rlib"]  # cdylib for Python, rlib for Rust

[dependencies]
# Core dependencies
ndarray = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
chrono = "0.4"

# Python bindings
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"  # For numpy array conversion
pythonize = "0.20"  # For serialization
bridgestan = { version = "2.7.0", features = ["download-bridgestan-src"] }

[package.metadata.maturin]
name = "seer"

[dev-dependencies]
approx = "0.5"
criterion = "0.5"

# Maturin will use this for building Python wheels
[build-dependencies]
pyo3-build-config = "0.20"
