name: Build CmdStan Binaries

on:
  workflow_dispatch:  # Manual trigger with options
    inputs:
      build_linux:
        description: 'Build Linux binaries'
        required: false
        default: true
        type: boolean
  push:
    paths:
      - 'stan/prophet.stan'
      - '.github/workflows/build-stan-binaries.yml'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build Linux binaries
        run: |
          chmod +x build_stan_binaries.sh
          ./build_stan_binaries.sh

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stan-binaries-linux
          path: stan/linux/*
